### ISSUE TITLE
Compatibility problem with IE11

### ISSUE THREAD

**Issue by prousseau** [sindresorhus/is-absolute-url#10]
It seems that there is a compatibility issue when moving the library from 2.1 to 3.0 with IE 11

It seems like that IE11 does not support the Arrow function used within this new version

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
