### ISSUE TITLE
scheme-relative is absolute?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/is-absolute-url#2]
https://github.com/sindresorhus/is-absolute-url/blob/master/test.js#L9

I'd think that it should be `false`.

**Comment by sindresorhus** [comment]
Why?

**Comment by stevenvachon** [comment]
Because `//url.com/` means nothing without a base. If its base is http, then it's an http url. If its base is hops, then it's an https url. It's a relative url.

**Comment by stevenvachon** [comment]
Unless you're referring to `//path/` where `//` denotes a host. In which case, such logic should be toggle-able.

**Comment by sindresorhus** [comment]
Hmm, good question. You could argue both ways for it. Yes, it's protocol-relative, but it's still an URL that resolves to an absolute resource, not a relative path.

// @kevva @shinnn @floatdrop @stevemao Thoughts?

**Comment by stevemao** [comment]
Seems to be an absolute to me but @stevenvachon has a very good argument..

**Comment by arthurvr** [comment]
Personally I'd go for `false` but it's just a feeling of mine. Both are valid arguments.

**Comment by shinnn** [comment]
I expect is-absolute-url to return `true` in this case.

A new option meets both requirements?

```js
// Just a casual idea

isAbsoluteUrl('//github.com', {includeProtocolRelative: false}); //=> false
isAbsoluteUrl('//github.com', {includeProtocolRelative: true}); //=> true
```

**Comment by stevenvachon** [comment]
Also, just look at the name: protocol-*relative*, scheme-*relative*.

**Comment by stevenvachon** [comment]
All URLs resolve to absolute when they have a base URL.

**Comment by stevenvachon** [comment]
`//github.com` resolves to http in the browser because of the page it's on is used as a base. Taken out of that context, how would it know to resolve to http or https, or even anything else?

**Comment by sindresorhus** [comment]
@stevenvachon It's absolute in the sense that it's not a relative path. What's your use-case needing it to be something different? I think the current behaviour is the most sensible, and unless you have a good use-case, I would say it only needs doc clarification.

**Comment by stevenvachon** [comment]
Parsing URLs in HTML for example wouldn't know whether to use http or https unless `url.resolve()` were used.

**Comment by sindresorhus** [comment]
Hmm...

From [Python docs](https://docs.python.org/2/library/urlparse.html):

>  If url is an absolute URL (that is, starting with // or scheme://)

But then from [StackOverflow](http://stackoverflow.com/a/27034171/64949):

> A relative URL must be either a scheme-relative URL, an absolute-path-relative URL

-

I guess it makes more sense to follow the latter as it's from the `URL Standard`.

**Comment by stevenvachon** [comment]
The URL Standard is split across HTML and URL specs. It's kinda messed up.

**Comment by kevva** [comment]
Both is correct here imo, but I would expect `//` to be absolute.

**Comment by stevemao** [comment]
Maybe this could return `undefined`?

**Comment by kevva** [comment]
No.

**Comment by stevenvachon** [comment]
```js
// isAbsolute(url, slashesDenoteHost);

isAbsolute("//localhost/"); //-> fase
isAbsolute("//google.com/", true); //-> true
```

**Comment by kevva** [comment]
Boolean arguments is nasty.

**Comment by stevenvachon** [comment]
```js
isAbsolute("/google.com/"); //-> isAbsolute.RELATIVE === 0
isAbsolute("http://google.com/"); //-> isAbsolute.ABSOLUTE === 1
isAbsolute("//google.com/"); //-> isAbsolute.PROTOCOL_RELATIVE === 2
```
also pretty nasty

**Comment by stevemao** [comment]
I was thinking maybe the return value couldn't be a simple `true` or `false` but a enum. So I kinda like @stevenvachon 's solution.

**Comment by stevenvachon** [comment]
Consider [this situation](https://github.com/nodejs/io.js/issues/1790).

**Comment by imyller** [comment]
`//` denotes a protocol-relative URL, also called as `network-path reference` in the spec. Absolute begins with `/` and relative without slash character.

See my comments at nodejs/io.js#1790

**Comment by kevva** [comment]
So, conclusion is that it shouldn't be treated as a absolute URL?

**Comment by imyller** [comment]
The spec says that 
```
express a URI reference relative to the name space of another hierarchical URI
```

What happens when there is no *another hiararchical URI* is not specified. I personally, and in case of Node environment would parse it as local file path; meaning that is actually is badly formatted but functionally valid absolute path (at least in POSIX environments).

But when used with `url.resolve` it most definitely is not absolute if the spec is followed.

**Comment by imyller** [comment]
If singular `//something` is treated as file path, it is not actually valid as it has double slashes, but those are ignored by most OS's. 

For reference I just tested with Python `os.path.isabs` and it also considers `//something/something` paths as *absolute local file paths* by returning `True`

So `//` has dual nature depending on the context, with a base URL it is not absolute, but without a base URL it can be interpreted as an absolute local path.

**Comment by kevva** [comment]
The intent of this repo is to check if an URL is absolute so in this case we should return false.

**Comment by imyller** [comment]
Exactly.

**Comment by imyller** [comment]
Do not however, that local file paths can also be URL ;)

**Comment by imyller** [comment]
So if this library chooses it can treat URLs without protocol given as being `file:`, `http:`; what ever is the most appropriate. This depends on the environment I think. 

For example browsers default to `http(s)` and local environments often to `file`. 

And then there is the option is to demand a specific protocol for all inputs and fail if its not provided.

**Comment by sindresorhus** [comment]
@stevenvachon Would you be able to do a doc update for #3?
